In [4]:
import numpy as np
import scipy
import pandas as pd
import matplotlib.pyplot as plt
import os
import struct
import math
import time
import importlib
import sys
from tqdm import trange


sys.path.append('..')
from lib.beta_functions import read_spec

In [5]:
spec_dir = "../example_data/example_spec_files/"

spec_files = [el for el in os.listdir(spec_dir) if el.endswith('.spec')]
nfiles = len(spec_files)
print(f"{nfiles} spec files found")

81 spec files found

In [156]:
print("read_spec() function")
print("--------------------")
t0 = time.time()
shead = [[]] * nfiles
ehead = [[]] * nfiles
spec = [[]] * nfiles
for i, filename in enumerate(spec_files):
    shead[i], ehead[i], spec[i] = read_spec(spec_dir+filename)

tf = time.time()
print(f"Elapsed time: {tf-t0:.4f} s ({(tf-t0)/nfiles * 1000:.3f} ms/iteration)")

read_spec() function
--------------------
Elapsed time: 1.7064 s (21.066 ms/iteration)

Test a new method: numpy.fromarray() 


DO NOT USE: 

https://numpy.org/doc/stable/reference/generated/numpy.fromfile.html
Do not rely on the combination of tofile and fromfile for data storage, as the binary files generated are not platform independent.

struct, but different:

In [7]:
a = "asdf" 
b = 12.7 
c = int(5)
# d = np.array([1,2,3,4], dtype=float)

fmt = '<8s1d1i'

print(struct.pack(fmt, *[a.encode('UTF-8').ljust(8),b,c]))
print(struct.unpack(fmt, b'asdf    ffffff)@\x05\x00\x00\x00'))

b'asdf    ffffff)@\x05\x00\x00\x00'
(b'asdf    ', 12.7, 5)

In [8]:
filename

'37222884.spec'

In [166]:

# this is actually pretty fast
def read_spec2(filepath):

    f = open(filepath, 'rb')
    f.seek(0, 2)
    file_size = f.tell()
    f.seek(0, 0)

    spec = []

    shead = {}
    ehead = {}

    junk, shead['ispec_method'], shead['ntwind'], shead['nf'], \
        shead['twindoff'], shead['dt'], shead['df'] = struct.unpack('4i3f', f.read(28))
    
    ehead_data = struct.unpack('2i40s40s3i28s11f5i', f.read(192))
    junk1, junk2, ehead['efslabel'], ehead['datasource'], ehead['maxnumts'], ehead['numts'], ehead['cuspid'], strs, ehead['qlat'], ehead['qlon'], ehead['qdep'], ehead['qsc'], ehead['qmag1'], ehead['qmag2'], ehead['qmag3'], ehead['qmoment'], ehead['qstrike'], ehead['qdip'], ehead['qrake'], ehead['qyr'], ehead['qmon'], ehead['qdy'], ehead['qhr'], ehead['qmn'] = ehead_data
    ehead['qtype'], ehead['qmag1type'], ehead['qmag2type'], ehead['qmag3type'], ehead['qmomenttype'], ehead['qlocqual'], ehead['qfocalqual'] = [strs[4*i:4*i+4].decode('UTF-8').strip() for i in range(7)]
    ehead['efslabel'] = ehead['efslabel'].decode('UTF-8').strip()
    ehead['datasource'] = ehead['datasource'].decode('UTF-8').strip()

    # 20 empty fields
    dummy = struct.unpack('20i', f.read(80))

    ba = f.tell()
    # pos 300

    # here are the spec objects
    ts1fmt = '2i' + 5*'8s' + 13*'4s' # 100 bytes 20 elements
    ts2fmt = f'6i18f22i{shead['ntwind']}f{shead['ntwind']}f{shead['nf']}f{shead['nf']}f' # 184 + 8*(stwind + nf) bytes 46 +ntwind+nf elements
    tsfmt = ts1fmt+ts2fmt # 284 + 8(ntwind*nt) bytes

    nel = 66 + 2*shead['ntwind'] + 2*shead['nf']

    tsbts = (284 + 8 * (shead['ntwind']+shead['nf']))
    nts = int(np.floor((file_size-ba) / tsbts))
    fmt = tsfmt * nts    # numts*(284+8(ntwind*nt)) bytes
    bts = nts*tsbts
    tsdata = struct.unpack(fmt, f.read(bts))
    
    spec = pd.DataFrame([tsdata[nel*i+2:nel*(i)+66] for i in range(nts)])
    # print(tsdata)
    f.close()

    return shead, ehead, spec

In [174]:
print("read_spec2() function")
print("--------------------")
t0 = time.time()
shead = [[]] * nfiles
ehead = [[]] * nfiles
spec = [[]] * nfiles
for i, filename in enumerate(spec_files):
    shead[i], ehead[i], spec = read_spec2(spec_dir+filename)
    # print(ehead[i])
tf = time.time()
print(f"Elapsed time: {tf-t0:.4f} s ({(tf-t0)/nfiles * 1000:.3f} ms/iteration)")

read_spec2() function
--------------------
Elapsed time: 0.4531 s (5.593 ms/iteration)

In [165]:
spec

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,b'APL ',b' ',b' ',b' ',b' ',b'HNE ',b'CI ',b' ',b' ',b' ',...,0,0,0,0,0,0,0,0,268,1808
1,b'APL ',b' ',b' ',b' ',b' ',b'HNN ',b'CI ',b' ',b' ',b' ',...,0,0,0,0,0,0,0,0,268,1808
2,b'APL ',b' ',b' ',b' ',b' ',b'HNZ ',b'CI ',b' ',b' ',b' ',...,0,0,0,0,0,0,0,0,268,1808
3,b'AVM ',b' ',b' ',b' ',b' ',b'HHZ ',b'CI ',b' ',b' ',b' ',...,0,0,0,0,0,0,0,0,268,1808
4,b'AVM ',b' ',b' ',b' ',b' ',b'HNE ',b'CI ',b' ',b' ',b' ',...,0,0,0,0,0,0,0,0,268,1808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,b'WRV2 ',b' ',b' ',b' ',b' ',b'HNZ ',b'CI ',b' ',b' ',b' ',...,0,0,0,0,0,0,0,0,268,1808
208,b'WVP2 ',b' ',b' ',b' ',b' ',b'EHZ ',b'CI ',b' ',b' ',b' ',...,0,0,0,0,0,0,0,0,268,1808
209,b'WVP2 ',b' ',b' ',b' ',b' ',b'HNE ',b'CI ',b' ',b' ',b' ',...,0,0,0,0,0,0,0,0,268,1808
210,b'WVP2 ',b' ',b' ',b' ',b' ',b'HNN ',b'CI ',b' ',b' ',b' ',...,0,0,0,0,0,0,0,0,268,1808
211,b'WVP2 ',b' ',b' ',b' ',b' ',b'HNZ ',b'CI ',b' ',b' ',b' ',...,0,0,0,0,0,0,0,0,268,1808

In [273]:
def read_spec_df(filepath):
    """ only read certain fields. Need:
    
    event id, numts (actual, not ehead['numts']), qlat, qlon, qdep, qmag, qmag1type, spectra

    """

    f = open(filepath, 'rb')
    f.seek(0, 2)
    file_size = f.tell()
    f.seek(0, 0)

    spec = []

    # read in file header info
    f.seek(8, 0)
    ntwind, nf = struct.unpack('2i', f.read(8))
    f.seek(4,1)
    dt, df = struct.unpack('2f', f.read(8))

    # bytepos=28
    
    # bytes in one object in spec
    tsbytes = (284 + 8 * (ntwind+nf))
    nts = int(np.floor((file_size-300) / tsbytes))


    f.seek(96, 1)
    event_id = struct.unpack('i', f.read(4))[0]
    f.seek(4, 1)
    qmagtype = struct.unpack('4s', f.read(4))[0].decode('UTF-8')
    f.seek(20, 1)
    qlat, qlon, qdep = struct.unpack('3f', f.read(12))
    f.seek(4, 1)
    qmag = struct.unpack('f', f.read(4))[0]

    # bytepos=176

    f.seek(44+80, 1)
    # should be at bytepos=300 here

    # print(ntwind, nf, dt, df, nts, event_id, qmagtype, qlat, qlon, qdep, qmag)

    X1 = [[]] * nts
    X2 = [[]] * nts
    S1 = [[]] * nts
    S2 = [[]] * nts
    stid = [[]] * nts
    slat = [[]] * nts
    slon = [[]] * nts
    selev = [[]] * nts
    deldist = [[]] * nts

    ntfmt = f'{ntwind}f'
    nffmt = f'{nf}f'
    for i in range(nts):
        f.seek(8, 1)

        stname = f.read(8).decode('UTF-8').strip()
        loccode = f.read(8).decode('UTF-8').strip()
        f.seek(24, 1)
        chnm = f.read(4).decode('UTF-8').strip()
        net = f.read(4).decode('UTF-8').strip()

        stid[i] = '.'.join([net, stname, loccode, chnm])

        # print(stid)

        f.seek(100,1)
        slat[i], slon[i], selev[i], deldist[i] = struct.unpack('4f', f.read(16))
        f.seek(112+ntwind*8, 1)
        # X1[i] = np.array(struct.unpack(ntfmt, f.read(ntwind*4)), dtype=float)
        # X2[i] = np.array(struct.unpack(ntfmt, f.read(ntwind*4)), dtype=float)
        S1[i] = np.array(struct.unpack(nffmt, f.read(nf*4)), dtype=float)
        S2[i] = np.array(struct.unpack(nffmt, f.read(nf*4)), dtype=float)
    
    D = {
        'event_id':     event_id,
        'nts':          nts,
        'qlat':         qlat,
        'qlon':         qlon,
        'qdep':         qdep,
        'qmag':         qmag,
        'stid':         stid,
        'slat':         slat,
        'slon':         slon,
        'selev':        selev,
        'deldist':      deldist,
        's1':           S1,
        's2':           S2
    }

    df = pd.DataFrame(D)

    return df

In [275]:
print("read_spec3() function")
print("--------------------")
t0 = time.time()
shead = [[]] * nfiles
ehead = [[]] * nfiles
spec = [[]] * nfiles
for i, filename in enumerate(spec_files):
    df = read_spec3(spec_dir+filename)
    if i == 0:
        D = df
    else:
        D = pd.concat([D, df])
tf = time.time()
print(f"Elapsed time: {tf-t0:.4f} s ({(tf-t0)/nfiles * 1000:.3f} ms/iteration)")

read_spec3() function
--------------------
Elapsed time: 0.6644 s (8.202 ms/iteration)

In [276]:
D

,event_id,nts,qlat,qlon,qdep,qmag,stid,slat,slon,selev,deldist,s1,s2
0,37222540,172,35.721329,-117.528671,4.600,2.44,CI.APL..HNE,35.341492,-116.874641,959.0,0.654373,"[1.17082941532135, 1.4137331247329712, 1.40037...","[0.8401854634284973, 1.1720306873321533, 0.947..."
1,37222540,172,35.721329,-117.528671,4.600,2.44,CI.APL..HNN,35.341492,-116.874641,959.0,0.654373,"[0.42280036211013794, 0.827343761920929, 0.992...","[1.6650688648223877, 2.2811477184295654, 2.193..."
2,37222540,172,35.721329,-117.528671,4.600,2.44,CI.APL..HNZ,35.341492,-116.874641,959.0,0.654373,"[0.36582043766975403, 0.4798847436904907, 0.55...","[0.5959967970848083, 0.9146026372909546, 0.732..."
3,37222540,172,35.721329,-117.528671,4.600,2.44,CI.AVM..HHE,35.065620,-116.615494,708.5,0.992307,"[60.98057556152344, 97.85444641113281, 85.5788...","[187.08560180664062, 262.90093994140625, 262.4..."
4,37222540,172,35.721329,-117.528671,4.600,2.44,CI.AVM..HNE,35.065620,-116.615494,708.5,0.992307,"[0.41030752658843994, 0.7011973857879639, 0.90...","[0.3079068958759308, 0.43262091279029846, 0.47..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,37222884,212,35.634838,-117.581703,10.222,2.49,CI.WRV2..HNZ,36.007740,-117.890404,1070.0,0.448772,"[0.12256042659282684, 0.22943289577960968, 0.2...","[0.2697908878326416, 0.47541481256484985, 0.48..."
208,37222884,212,35.634838,-117.581703,10.222,2.49,CI.WVP2..EHZ,35.949390,-117.817688,1465.0,0.367863,"[5.759305953979492, 11.478775978088379, 12.715...","[6.081404685974121, 13.791723251342773, 13.576..."
209,37222884,212,35.634838,-117.581703,10.222,2.49,CI.WVP2..HNE,35.949390,-117.817688,1465.0,0.367863,"[0.3790879249572754, 0.6017147898674011, 0.669...","[0.6218292117118835, 1.1308197975158691, 1.075..."
210,37222884,212,35.634838,-117.581703,10.222,2.49,CI.WVP2..HNN,35.949390,-117.817688,1465.0,0.367863,"[0.357061505317688, 0.701852023601532, 0.65808...","[0.7317829728126526, 1.1347416639328003, 1.273..."
211,37222884,212,35.634838,-117.581703,10.222,2.49,CI.WVP2..HNZ,35.949390,-117.817688,1465.0,0.367863,"[0.2702253758907318, 0.4612032473087311, 0.786...","[0.5499007701873779, 0.8603150844573975, 0.873..."

In [181]:
print("simple read function")
print("--------------------")
t0 = time.time()
for i, filename in enumerate(spec_files):
    f = open(spec_dir + filename, 'rb')
    data = f.read()
    f.close()
tf = time.time()
print(f"Elapsed time: {tf-t0:.4f} s ({(tf-t0)/nfiles * 1000:.3f} ms/iteration)")

simple read function
--------------------
Elapsed time: 0.0111 s (0.137 ms/iteration)

In [250]:

# load entire file first
def read_spec4(filepath):

    f = open(filepath, 'rb')
    f.seek(0, 2)
    file_size = f.tell()
    f.seek(0, 0)
    data = f.read()
    f.close()

    spec = []

    shead = {}
    ehead = {}

    junk, shead['ispec_method'], shead['ntwind'], shead['nf'], \
        shead['twindoff'], shead['dt'], shead['df'] = struct.unpack('4i3f', data[:28])
    
    # print(shead)
    
    ehead_data = struct.unpack('2i40s40s3i28s11f5i', data[28:220])
    junk1, junk2, ehead['efslabel'], ehead['datasource'], ehead['maxnumts'], ehead['numts'], ehead['cuspid'], strs, ehead['qlat'], ehead['qlon'], ehead['qdep'], ehead['qsc'], ehead['qmag1'], ehead['qmag2'], ehead['qmag3'], ehead['qmoment'], ehead['qstrike'], ehead['qdip'], ehead['qrake'], ehead['qyr'], ehead['qmon'], ehead['qdy'], ehead['qhr'], ehead['qmn'] = ehead_data
    ehead['qtype'], ehead['qmag1type'], ehead['qmag2type'], ehead['qmag3type'], ehead['qmomenttype'], ehead['qlocqual'], ehead['qfocalqual'] = [strs[4*i:4*i+4].decode('UTF-8').strip() for i in range(7)]
    ehead['efslabel'] = ehead['efslabel'].decode('UTF-8').strip()
    ehead['datasource'] = ehead['datasource'].decode('UTF-8').strip()

    # # 20 empty fields
    # dummy = struct.unpack('20i', f.read(80))

    ba = 300
    # # pos 300

    # here are the spec objects
    ts1fmt = '2i' + 5*'8s' + 13*'4s' # 100 bytes 20 elements
    ts2fmt = f'6i18f22i{shead['ntwind']}f{shead['ntwind']}f{shead['nf']}f{shead['nf']}f' # 184 + 8*(stwind + nf) bytes 46 +ntwind+nf elements
    tsfmt = ts1fmt+ts2fmt # 284 + 8(ntwind*nt) bytes

    nel = 66 + 2*shead['ntwind'] + 2*shead['nf']
    # print(nel)

    tsbts = (284 + 8 * (shead['ntwind']+shead['nf']))
    nts = int(np.floor((file_size-ba) / tsbts))

    fmt = tsfmt * nts    # numts*(284+8(ntwind*nt)) bytes
    bts = nts*tsbts
    tsdata = struct.unpack(fmt, data[300:300+bts])
    
    spec = pd.DataFrame([tsdata[nel*i+2:nel*(i)+66] for i in range(nts)])
    # # print(tsdata)
    # f.close()

    return data

In [252]:
print("read_spec4() function")
print("--------------------")
t0 = time.time()
shead = [[]] * nfiles
ehead = [[]] * nfiles
spec = [[]] * nfiles
for i, filename in enumerate(spec_files):
    data = read_spec4(spec_dir+filename)
    # print(ehead[i])
tf = time.time()
print(f"Elapsed time: {tf-t0:.4f} s ({(tf-t0)/nfiles * 1000:.3f} ms/iteration)")

read_spec4() function
--------------------
Elapsed time: 0.8254 s (10.190 ms/iteration)

In [249]:
npdata = np.bytes_(data)

nel = 518
nts = 212

inds = 300 + np.arange(nts) * nel

[npdata[inds[i]:inds[i+1]] for i in range(nel-1)]

IndexError: index 212 is out of bounds for axis 0 with size 212

In [245]:
npdata

np.bytes_(b'\x18\x00\x00\x00\x02\x00\x00\x00\x96\x00\x00\x00L\x00\x00\x00\xcd\xccL\xbd\n\xd7#<\xab\xaa*?\x18\x00\x00\x00\x08\x01\x00\x00                                                                                \xef\x00\x00\x00\xef\x00\x00\x00\xe4\xf97\x02                            \x13\x8a\x0eB\xd5)\xeb\xc2P\x8d#A9\xb4\xd7A)\\\x1f@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe3\x07\x00\x00\x07\x00\x00\x00\x04\x00\x00\x00\x11\x00\x00\x007\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08\x01\x00\x00\x0c\x01\x00\x00APL                                     HNE CI                                              \xe1.\x00\x00\xe3\x07\x00\x00\x07\x00\x00\x00\x04\x00\x00\x00\x11\x00\x00\x006\x00\x00\x00\x00\x00\xc6\xc2\x00\x00\xc6\xc2\x00\x00\x80?\x00\x00\x80\xbf\x00\x00\x80\xbf\n\xd7#<\xf0\xd6cBY\x06\xf0\xc1\xb0]\rB\xd1\xbf\xe9\xc2\x00\xc0oD\xd1\xa1%?\x1a\x8d\x94C=b\xe9B\x02g\'B\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc6\xc2\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0c\x01\x00\x00\x10\x07\x00\x00\x00c\xceB\x80\xe3TB\xc0\x8e\x98\xc2@z\x90\xc2\x00\x7f\x8eA\x00aSB\x00\x08\xf4@\x00\xbc\xb3\xc2@*\x97\xc2\x80\xe6\x0fB@\x02\x84B\x008\xd8A\x00\xc8\x91@\x00\x84qA\x00\xfb\x96\xc1@<\xc1\xc2\x000\x15\xc1`A\x16C\x00\x0b\x10B\xe0\xc1.\xc3\x80\xe9\xd2\xc2\xc0\xbd\xc8B\x00K\xcfB\x00n\x13\xc2\x00J^\xc2\x00\xd6\xf9A\x80\x11bB\x00\xc0\xfb\xc1\x80\xe9\x9c\xc2\x00p0B\xc0O\xafB\x80jF\xc2\x80\xa4\x8c\xc2\x00\xed\xc3A\x00\x80\xf9\xbe@\xf4\xa4\xc2\x00\xc28\xc2\x80;\x8cB\x00M\xbeB\x00\x9a~A\x00z\xbc\xc1\x00\xe0\x0e@\x00@\x1cA\x00\xa9\x85\xc1\x00\xb9\x11\xc2\x00\xa0\xd4\xc0\x004\x9dA\x00Y\'\xc2\x80?A\xc2\x80\xfd,B\x00\x189B\x00\xac\x97\xc1\x00q\xcd\xc1\x00yLB\x80S\x8bB\x80YN\xc2\x80 \xb9\xc2\x00\xea\x7fA@\x92\x95B\x00e\x8eA\x00\x18{\xc0\x00\x08\xb5A\x00nW\xc2\xc00\xe6\xc2\x00\xaa\x00\xc1\x80\x03\x00C\xc0\x96\xc9B\x80\xd8}\xc2\xc0^\xb1\xc2\x80\x8ccB\x80\xd7\x98B\x80Pu\xc2\x80\x1d\xd9\xc2\x00\x0e\x00A\x800lB\x00\xd0\x00\xc2\x00^\xcb\xc1\x80\xc8\xbeB\x00\xd9\xafB\x80PY\xc2\x80\x19\x8d\xc2\x00\x13FB\x00`\xfeA\xc0\xe9\xd2\xc2\x00\xd9\xb4\xc2\x00\xca\x9aB@/\x01C\x00\x0c\x86@@\x96\xcc\xc2@\x03\xb8\xc2\x00n7\xc1\xc0\'\x89B@\xb8\xbaB\xc0F\x8aB\x00\xc0\n@@\xa4\xbd\xc2@\x13\xa4\xc2\x00/\xd4A\x801\x07B\x00y\x9d\xc1\x00.\xcd\xc1\x00\xec-\xc1\x80\xaccB\x00\xf9\x07C\xc0|\x81B@\x82\xba\xc2 \xf9\x05\xc3\x80\xb5h\xc2\x00s\x0fB\x80\xcf\xc8B@\xde\x89B\x808/\xc2\x00\x11\xab\xc2\x00+\xa8A\x80\xa6\xb3B\x00i\xef\xc1@\xd2\xbd\xc2\x00\xe8y@\x00y\xfdA\x00\xca4\xc1\x000?@\x80\x1blB\x00$\x9dB\x00T\xaf\xc1@\xd0\xe7\xc2\x80kQ\xc2\x00\x85\xe3A\x80\xd91B@\x02\x80B\x00=\x8aA\x80\xd7 \xc2\x00\xcb\xe6A\x00\x13\xc7A\x80\xbc\x90\xc2\x80C\x1e\xc2\x00@^@\x00"\x18\xc1\x00?\x8eA\x80\xa1\x8eB@\xba\xc2B\x00\xfb\xc0\xc1\xa0`*\xc3\x80\xa6\x95\xc2\x80\xff\xf9B\x80\x8b\xd4B\x00\xf5#\xc2\x00\x10\x1c\xc0\xc0\xbe\x94B\x80\x82\x14\xc2\x80:\xec\xc2\x00p\xe7\xbf\x00\x02\xebB\x004tA`\xbe\x03\xc3\x80\xc1U\xc2\x00\xbe\xc0B\x80K\xdaB\x00R\xf3A\x00z\xb8\xc1\x00)\xdc\xc1\x00\xf9:\xc2\x00\xddF\xc2\x00\x90\xe5\xc0\x00\xdb\xe4A\x80\x96cB\x00h\x97A\x80DI\xc2\x00\xc03A\x00#qB\x00\xb6\xe1\xc1\x00\xbb]\xc2\x00\x00\xe8=\x80\x914B\x00\xe0\xb1B\x80\xdc+B@\x8f\x83\xc2\x80\xf3B\xc2\x00\x00\x85=\x00\xbbf\xc2\x00R\x1a\xc1\x00\xd9\xd0B\x80\xb6\x16B\x8057\xc2\x00\x0c\x19\xc2\x00\xd0\x0e\xc0\x80CHB\x80]3B\x00\xd4\xbb@\x00j\x19\xc2\x80QC\xc2\x00\x847A\x00\x02\x1eB\x00|LA\x80\xc8"\xc2\x80\xb3H\xc2\x80\x86iB\x80\xdb\xdbB\x00\x8d\x90\xc1@\x1d\xdf\xc2\x00\x07\xb6\xc1@\x19\xb4B\xc0\xa5\x8cB\x00\xa02\xc1\x00\xfa]\xc1\x00\xab\xea\xc1\xc0\xaa\xd9\xc2\x00N\xce\xc1 \x88\tC\x00\x99\xf4B\x00\x14%A\x00T\xb7\xc2\x00G\xb7\xc2\x00g\xc1A\x80\xcfDB\x00\xc0\x83A\x00\x13PB\x00f\x9eA\x80\xe5\xba\xc2\x00\xa7e\xc2@R\xc8B@_\x98B@$\xc5\xc2\xa0\xcb\n\xc3\x00\x1a\xa6A\xa0\x93\'C\xc0+\xa6B\x80\xaaU\xc2\x00\x80\x93\xc0\x80\xbe\x14B\x80;"\xc2\x80\x18B\xc2\x00d<A\x00\xd2LA\x00\xc8r\xc1\x00\x1f\x87\xc1\x00\x84\x83\xc0\x80\xb3/B\x80s\xc1B\x00\xf2\x99A\x00\x81\xa5\xc2\x00\x96\xe7\xc1\x00\xbf\xdeA\x00\xc2mA\x80\x9d+B\x80\xc1\x16B\x00_\xf6\xc1\x80\x0cP\xc2\x80\xea\x19\xc2\x00X\x03@@4\x87B\x00\x81\x10B\x00\xe9\xd4\xc1\x00\x84\xcfA\x80\xe8\x0bB\x00\x15\x06\xc2\x00@\xe2A\x00\xac\x9aB\x80V\x85\xc2@\xe8\r\xc3\x00\x94nA\xe07\x05C\x00\xc3\xddA@\x0b\x94\xc2\x00\x90\x1cA\x80\xab\x99B\x00$\xad\xc0\x00\x12\xd3\xc1\x80\xb49B\x00D\x86@\x00\x17\x99\xc2\x00\xfe\xb9\xc1\x00\x1a\x90B\x00S\x7fB\x80\x9f\n\xc2\x80\xc4\xa9\xc2\x00\xb5\xa6\xc1\x00\xd1{B\x80\xf9\xcdB\x80\x8c\xabB\x00\xb2\xff\xc1\xc0\xe7\xf9\xc2\x80\x98\x11\xc2\x00Q\x92B\x00\xc2\x1eA\xc0$\xa6\xc2\x00TD\xc1\x00\x90\x8bB\x80(\x02B\x00NFB@\xc3\xc1B\x00\xd8\x84\xc1 \xdc0\xc3\x00\xa4\xbf\xc2@\x05&C@\x8e1C@s\x9e\xc2@3\x0e\xc3\x00\x0c\xedA\x80\xa4VB\x00b\x03\xc2\xa5P(?\x15\x1f]?\xdf\xf98?\x97\xa1<?\xd8\x837?\x9f\x8bs?\xb6\xd4\x95?\x19\xe0\xb5?\x0ep\xef?\xff\xde\x93@f\xcb\xa1@\xd0\x99\xab@\xa2E\xb0@\xb1{\xae@\xfb\xb1\x0cAP\xf0-A\xa0q2A\x0c\xbf6A\xa5\xe68A\xc2\xfePAm\xe6+Api\x0cA,\xdb*AD\xe03A\xb7OhA\xbb\xc2\x8bAH\x9a\x94A\x1e\xda\x9cA\x16@\x89A\xcd\x1fiA>\x80eA\xcf@\x16A\x94q,AV\\+A\xa6J^A6\x86\xb4A\x15\x9f\xbaA\x01\xca\xbcA\xd6\x8c\xa8A\xf3\xf0\xa3A"!\x85A\x84\x97\x1eA\xd4`\xe4@\x1bS\xec@\xb5\xcd\x9b@\xb4\xbc{@.\xdf\x8c@4\xa9\x8c@m}O@\x17\xc1i@\xd1\x85\x88@-5m@(c+@\xe9\xa7&@bl$@\x04V\x14@M)\xc0?\x8fN\x8d?c\x11\x84?\x16\xe1y?\xc8\x81i?\xb2\xaaV?L\xb7A?\x91\xde\x00?\x8f\xa4\xc1>\xec\x84\x1c>\xa7?\xcc=A\xa9\xcd=\x91\x87\xba=\xf5\x0f\xe7<\x1aK\x1c<\x9a\x7f\xb9:\xc4\x08\x0c:\xf2\x94\xdf9T`\x939\xaf\x89\x9f9Il\xe4>\x1f\xae&?\xc1{\x14?\xf8\x9e\t?Ll\xe4>\xd3\'\xfb>\xeb94?\xee\xda\x89?\xed\xcc\xed?\xc1R\x92@\xfbn\xac@\x1f\x88\xad@B*\xb9@ /\xc4@#\xe9\xcc@\xac\xea\x0bA\xa8\xe9\x07A\xb2^\x11A\x90\xcc\x06AEo;A\x86\xa1-A\x0e\xd9\nAuf.A\xfd\x83SA\xed\x05\x98A4\x8e\xaaA\x0ff\xaeA2\xd0\xa5A\xa3W\xabA\xfc\xd0zA\xcc\x12BA.3\x15A\xf7\x92!Ai\xd2.AS4MA\xde+\x90AH\x11\x8dA\xe3\xae\x84A\xa6\xc9\x82A\x16\xbb\x92AR\xfb~ANNhA\xe0)0A1\x03\x16A_\xbf\xb3@\x8b\x90\xb9@\x01&\xb1@\xc8\xf6\xd8@\xa1\xa3\xdd@\x16T\xbe@?\x1a\xba@z|\x94@\xc7a\x97@\xefD>@P\x92\x1d@\xe6i\x14@\xc7\x7f\x05@C"\xc0?\x90\xfb\xb3?*\xfa\xae?<wn?v\x137?XT1?o1\x0f?\x0cK\xb2>@\x17\x07>!~\xe1=\xdc#\xd1=\xdd\x02\x81=\x02s\xae<v\x90\x80;\xb3*\x93:\x9c\xaf\x969\x01^\xa09yN\xc39\x11\xa6\x8c9\x10\x07\x00\x00\x0c\x01\x00\x00APL                                     HNN CI                                              \xe1.\x00\x00\xe3\x07\x00\x00\x07\x00\x00\x00\x04\x00\x00\x00\x11\x00\x00\x006\x00\x00\x00\x00\x00\xc6\xc2\x00\x00\xc6\xc2\x00\x00\x80?\x00\x00\x80\xbf\x00\x00\x80\xbf\n\xd7#<\n\xd7cB%\x06\xf0\xc1\xb0]\rB\xd1\xbf\xe9\xc2\x00\xc0oD\xd1\xa1%?\x1a\x8d\x94C=b\xe9B\xe8f\'B\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc6\xc2\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0c\x01\x00\x00\x10\x07\x00\x00\x00Pu\xc1\x00XR\xc2\x00`P\xc2\x00P\xabA\x00\xdb\x98B\x00<\x9fA\x00\x80\t\xc1\x00\xc4\xf2\xc1\x00xO\xc2\x00\xa4&B\x00S\x92B\x00\xa0\xeb\xc0\x00v;\xc2\x00\xf0\xfa\xc1\x00H\x12A\x00\x00\xba\xbe\x00\x84\x11\xc2\x00\xf0A\xc1\x00\x08\xdbA\x00\xc3\x88B\x00\x8ahB\x00\x94\x04\xc2\x00\x1c\xcd\xc1\x00\x0c\xafA\x00\x98d\xc2\x00\xd1\x8e\xc2\x00~\x1aB\x00t\x0bB\x00\xac\x1d\xc2\x00j\x08B\x00\xbd\xacB\x00@\xe5\xc0\x00\xa6\x07\xc2\x00@\xcb\xc1\x00\xb4B\xc2\x00\xb8\xaeA\x00\xb4\x9dB\x00\x80\xa2@\x00\xbaL\xc2\x00\xb2\x07\xc2\x00p\xb3\xc1\x00\x00\x11?\x00NfB\x00)\x89B\x00\x88\xc1\xc1\x00\xec\x91\xc2\x00\x8c\xd2A\x00J2B\x00\xde+\xc2\x00\x00\xe5\xbe\x00@\x03B\x00\xde\x14\xc2\x00\xb0\xb3\xc1\x004\x1eB\x00`\xb8A\x00\xe29\xc2\x00\xe8O\xc2\x00L\xa4A\x00&SB\x004\xeeA\x00\x1c\x0bB\x00@\xa2A\x00\xfal\xc2\x00\xf6p\xc2\x00`\xbf\xc0\x00\x14\xe6A\x00\x0c\x83B\x00\x18\xd6A\x00\x00E\xc2\x00\x05\x9a\xc2\x000\x80\xc0\x00\x8b\xc2B\x00\x02\rB\x00\x0e\x84\xc2\x00\x18\xb4\xc1\x00\x022B\x00@_@\x00 S\xc2\x00@\x01\xc0\x00\xf68B\x00\x98\x1fA\x00\x80<\xc1\x00\x00\xc7@\x00\xe6\x0eB\x00\x90cA\x000\x17\xc2\x000\xa1\xc0\x00\xbc\x89A\x00d\xae\xc1\x002\x0e\xc2\x00\xd8\x14\xc1\x00\xd8\x1cB\x00@C\xc0\x00LA\xc2\x00\xd2\x04B\x00\xc8\x13B\x00\xd82A\x00\xd0^B\x00@\x82\xc0\x00\xab\x8b\xc2\x00L,\xc2\x00\x80\xd6?\x00\xe8nA\x00\xb8\xa0\xc1\x00\xb8rA\x00\xb8\x1aB\x00\x98e\xc1\x00\xa0\x1a@\x00\xd0\x9a\xc0\x00lG\xc2\x00\xc8\xb0\xc1\x008\xb3A\x00\x9c&B\x00\x98<B\x00\x9eiB\x00\x00\x1a\xbf\x00\xc4\xdf\xc2\x00\xc0\xa1\xc2\x00\x96\x15B\x00H\x83B\x00\x0c\xc7A\x00\x04\x87\xc1\x00\x08\xbf\xc1\x00\x04\x95\xc1\x008\x12\xc1\x00\x84MB\x00\x04\xd5A\x00\xa6v\xc2\x00\xd8\tA\x00\x80\x18B\x00\xaaE\xc2\x00\xb8\rA\x00\xf0\x8cA\x00_\xba\xc2\x00f\x08B\x00\xe2\x13C\x00\xd0R\xc1\x00\xda\x9e\xc2\x00D\xff\xc1\x00h\xa7\xc1\x00\xb4\x96A\x00\xa8\xaaA\x00\xd0\x06\xc1\x00l\x95\xc1\x000\x82@\x00R(B\x00\x18\x19A\x00\xc8\x12\xc2\x00\x08;\xc1\x00\x10\xa2@\x00\x9c\xa7\xc1\x00p\xceA\x00%\x9bB\x00@G\xc1\x00\xf1\xcb\xc2\x00\xdao\xc2\x0047B\x00\x9b\xa4B\x00&+B\x00\xb8\x18A\x00\xf4\xb0\xc2\x00\x00\x04\xc3\x00P\x82A\x00\x96\xaeB\x00\x10.B\x00 .B\x00\xc0o\xc1\x00\x00K\xc2\x008\x90A\x00p\xa8@\x00\x02s\xc2\x00\x02L\xc2\x00\x14\xbeA\x00\x0e$B\x0088\xc1\x00\x04\xb4A\x00\x0c\xf8A\x00\x16\x17\xc2\x00\x1c\xd2\xc1\x00\xf0\xb9A\x00\xec\x9dA\x008\x94\xc1\x00\xb03A\x00\xe0\x7fA\x00\x98\x97\xc2\x00H\xea\xc1\x00\xf6wB\x00\xb0\x8fA\x00\xb8\xb7A\x00\xea\'B\x002v\xc2\x00"\xe2\xc2\x00\xb0\xd6@\x00t\xb4B\x00\xc0\xd8?\x00\x84\xf0\xc1\x00\xb0\xcfA\x00x\x9a\xc1\x00Jz\xc2\x00\x00\r\xc1\x00\xc8;B\x00\x80\xe5A\x00\x90\xa5@\x00\x00\x13A\x00X6\xc2\x00\x00\xd4>\x00i\xcfB\x00Z.\xc2\x00\xa0\x18\xc3\x00t\xcbA\x00^\xa3B\x00\xe8\xc8\xc1\x00\xa8\x0cB\x00\xb8\x1cB\x00\xe2\x06\xc3\x00\xbe\x96\xc2\x00\xde\xf7B\x00\x9auB\x00\x86(\xc2\x00h.A\x00\xc8Q\xc1\x00\x86W\xc2\x00@rA\x00\x18\xc5A\x00\x86\x18\xc2\x00\x10\xd5\xc1\x00\x8c1B\x00\x00\x9bA\x00\x9a,\xc2\x00\xf4\xacA\x00\x88bB\x00\x9c/\xc2\x00\xa0Z\xc2\x00|(B\x00\xe0\xfeA\x00H\xa5\xc1\x00\xb0\x9c\xc0\x00<\xc1\xc1\x00\xae8\xc2\x00\xc4\xf8A\x00\xb7\x87B\x00\xb24\xc2\x00\xe1\x8e\xc2\x005\x8fB\x00^FB\x00\xce`\xc2\x00\xb8\xdcA\x00\xa0\xaa@\x00\xed\xc2\xc2\x00\xa0\x8cA\x00,\x8dB\x00\xd2\x02\xc2\x00\x8c\xd3\xc1\x000\x9a@\x00\xd68\xc2\x00\x80\x89@\x00\xa6\xdaB\x0085B\x00\xf2\xa9\xc2\x00\xf0\xb3\xc2\x00PC\xc1\x00X\xf0A\x00&\x15B\x00*8B\x00\x00^\xbe\x00\xf4}\xc2\x00\xcc\x97\xc1\x00\x88xA\x00\xe0s\xc1\x004\xc6A\x00hpA\x00\x83\x8a\xc2\x00\xe8\x1b\xc1\x00\x11\xbcB\x000\x18A\x00\x0b\xe2\xc2\x00\x08e\xc2\x00\x0cqB\x00\x04\x98B\x00\xf0\xa3A\x000\xa0\xc0\x00\x0cA\xc2\x00\x91\xb5\xc2\x00`\x80\xc0\x00~\x83B\x00\xe8FB\x00\xf23B\x00hX\xc1\x00\x15\x98\xc2\x00$E\xc2\x00\x10\xff@\x00\xc8\xd7A\x00P\xc9\xc0\x00\x005?\x00xsA\x00p\x98\xc1\x00\xa4\x87A\x00\xdaeB\x00\xa0\\@\x00@6\xc2\x89\xc5\xcb>*\xaf\x19?\xfb!\r?\xdd\xf9\x01?\x83\xa9\xc4>>\xac\xe8>-\x9d\x92?\x19\x06\xc9?i\xad\xd2?\x01\xdd=@\x87\xa7X@\xc9(Y@}\x8a\x93@\xdeL\xae@\xdd\xeb\xb0@+!\x9b@bn\x97@\xca\xb6\x0eA2\xbe\x05AL\xe6\x05A)U\rA\x86G\x03A\xf8\xaa\x12A\xb0\xa6\x08A\x1d\xe8\tA4\x04 As\xc5*A\xf6\xe5\'A\x81v6Aj\xf3\x10A\x8b]\x17A~\x9c\xba@\x11\x9c\xc6@\x1f\xfe\xcc@A\xa1\xb9@\x85\x12\x03A)\xa6\x00A\x97%\tA\x98[\xe9@\x88q\xf5@\x83Z\x02A(0\xea@n\x11\x15A?\xcf%Ac\xde\x19A\xf7m\x1dAQX\x11A\xb3,\nA\x98\xf4\xba@\xc6\xb3\x90@\xf4\x8e\xa3@\x88\xb7\x95@\x90\xc7z@4Xk@\xb9\x8f\x8e@\xdcEg@hS\'@J\xca/@\x9bh\x14@g\xb3\x13@\x1e\xab\xdb?U\xbe\xbd?m\xb5O?\xd6\x0c\x05?D_\xee>C\x9e\xca>\xcdn6>\x95\xb26>=\xa5\xd8=\xe3\xf2*=\xa7T\x86;Z\x00\xcc:u;\x819\xf2\xcc\xba9P\x1e\x019\xc2CF9\xc3\x00\x8f>`\xb8\xc1>`\xf6\xbf>\xd1q\xda>\xfe\x7f\xfe>E\n+?d\x93??\xc7\xf2\x81?\xf5\xa9\x8b?zD\x12@\xdc\x84\x16@G\x91&@\xcf8*@\xa6JW@a\x98\x82@/\x85\x91@\xde\x81\x94@\xfb\xb6\xbd@\x99J\xef@>\n\x1aA)L A\xb1\x9f\x17A\x7f\xb1#A~C\xd9@\xa2\x86RA\x03\x03gAWcpAX\x99nA\x0ef>A\x89\xb43A\x0cm\x0eA\x89C\xcb@\\\xad\xc6@\xf2\xd4\xff@\xdb\xab\xfc@\x930\xe8@[z\xe0@\xa2\xfd\xe7@\xd5|\xe1@s\xae\x8d@\xb2\xb2\x82@B\x89\xa5@\xb8\xfesA\x98\x14\x84A\xb6\t\x84A\x1d\xa4\x82A\xc5\x04\x87A\xe8\xcb\x82A\x83\xb1\xf3@\x95g\xac@\xf2\x00\xac@\xbd]\xa7@\'\xf7\x92@}\xeb^@\xf5\x011@8\xc3$@\xb4\xed\x1c@<\x89\x03@A\xcb\x01@}\xf9\xe6?.h\xc6?\xd7\xd4\xa1?v#q?\xbe\xa7\xcf>\xd2\'\x99>\xd6\xc7\x8d>\x15\xd0x>\x12\xca0>\x00\xa5\xe1=j` =\xact5;\xaa\x99\x90:@\xb5\xd39\xcd\xe3\xa99\xad\x13\xde8\x86w\x179\x10\x07\x00\x00\x0c\x01\x00\x00APL                                     HNZ CI                                              \xe1.\x00\x00\xe3\x07\x00\x00\x07\x00\x00\x00\x04\x00\x00\x00\x11\x00\x00\x006\x00\x00\x00\x00\x00\xc6\xc2\x00\x00\xc6\xc2\x00\x00\x80?\x00\x00\x80\xbf\x00\x00\x80\xbf\n\xd7#<\n\xd7cB%\x06\xf0\xc1\xb0]\rB\xd1\xbf\xe9\xc2\x00\xc0oD\xd1\xa1%?\x1a\x8d\x94C=b\xe9B\xe8f\'B\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc6\xc2\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0c\x01\x00\x00\x10\x07\x00\x00\x00\xaa|\xc1\x00\xbbcB\x00\x94QB\x00|\xfc\xc0\x00h\xaa\xc2\x00p\x13\xc1\x80\n\xa6B\x80\xe1NB\x00\x00=>\x00m\x10\xc2\x00\x8e\n\xc2\x00\xa8\xf2@\x00=\x03B\x00\xec\xff\xc1\x00&=\xc2\x00\xdf\x01B\x80b\x01\xc2\x00\x932\xc2\xc0\xbc\xc6B\x80&\xadB\xc0y\x8c\xc2\xc0\x93\xcd\xc2\x80\xf3\x9eB\xa0t\tC\x80{\x12\xc2\xe0\xaa,\xc3\x00\xeb\xe5\xc2`\xd1\rC`\xcb*C@ \x9e\xc2\xc0\xa9\xe7\xc2\x00xA\xc1\x00\xf0\x86A\x00S\x08B@\x1c\xd5B\x80L\x04C\xc0\x0e\x9d\xc2\xc0Yi\xc3@.\x8b\xc2\x00N\xfdB\x00\x9e\x03C\x00\x91\x89\xc1\x00\xfe\xe1\xc2\x00\x0cY\xc2\x80\xd9\rB\x00`\xb0B\x80\x98$B\x00\xa6\x1f\xc2\x00\x00\xa3=\x00\xa8\xc5\xc1\xc0\x8c\x8b\xc2\x80|\x90B\x80\xd3jB@\xc2\xf6\xc2\xc0\xcc\xae\xc2\x005\xcaB\xa0\x93\x04C\x00\xf7\xad\xc1\x80\x12\xc7\xc2\x808E\xc2\x00Q\x83A\x00\x8fxB\x80f*B\x00\x90\x87?\x80\xe2\x0c\xc2\xc0\x8c\x9c\xc2\x00P7A@\xeb\xc6B\x00{p\xc2@n"\xc3\x00\x97\xb4A`\x14XC\x80\x8d\xbfB\xe0\x12\x18\xc3\x00\xa6\xa1\xc2\x00\xbchB\x00\x95 \xc2\x00\xbcp\xc2\x00\xa2\x96B\xc0\x94\xb7B@\x91\xb5\xc2 \xd8\x06\xc3\x00\xe3\xedB\xe0j.C\x80\xb2\t\xc2\xc0\xe6\xef\xc2@y\xc2\xc2\x00\xdeOA\x80\xfc\x07C\x80`\xa6B\x80=\x86\xc2\xc0R\xf6\xc2\x80[\x81\xc2\x00\x96\x00A\xc0\x89\xbdB\xc0\xfb\xb9B\x00LL\xc2\x80\xbe\xf0\xc2\x00\xe8\x1dA\x80;\xf5B\x801\x01B\x80\xf5E\xc2\x00\x8a\xc1\xc2\x80)\xe5\xc2\x80\xb7hB`i\x06C\x00P\x85\xc0\x00\xc9P\xc2\x00\xc2\xe7\xc1\x00Bd\xc1\x80\xe5}B\x00\xc3lB\x00x<\xc2@O\xc8\xc2\x00\xc0 \xc2\xc0\x9e\xb0B\x80\x8b\xa6B\x00) \xc2\xc0\xa5\x89\xc2\x00tU\xc1\x00(\x8c\xc0\x00@U?\x00\xf6`A\x00p_\xc0\x00\xef\xafA\x00\xa8|@\x00D\xa5A\x80R\x86B\x00V\xa2\xc2\xa07\x12\xc3\x00\xa4HA\x00\x07\xbeB\x00\xd9\rB\x00\x9f\x92\xc1\x00\xdf\xf8\xc1\x00+\xd3\xc1\x00\xe8\x14@\x00.\x02B\x00L\\A\x80\x97\xa7\xc2\x00\x9d\xfe\xc1@\xe2\xd9B\x00\xac\xb3@\x80\xbe{\xc2\x80J;B\x00\xe0\xe3?@\x0c\x18\xc3\x80F|\xc2 \xf4(C\xc0h\x16C\x00\xd4\xb2\xc2\xe0\xbbb\xc3\x00\x00\xf3\xbe@\x0faC\x00:kA\x806\xff\xc2\x00tq\xc1\x00\x80\x9b@\x00`\xc3\xc1\x00\xe1T\xc2\x00\x18\xc0@\x80\xff\xa3B\x00\xd4\xad@\x80f\x1f\xc2\x00\r\xb7\xc1\x00\xe0\xf2@\x00\x80A\xbe\x80\xfd!\xc2\x00\xe8sA\x00\xa4\xc7A\x00M\x8bA\x00<\xc5A\x00\xd7\xe1\xc2\xe06\x05\xc3\x804LB\x00\x07\xbdB\x00\xa4\x89A\x00\xd4\xad@\x00\xd5\x9a\xc1\x00\x9b{\xc2\x00l\xd3\xc1\x006@B\x80\x16"B\x00\x93\x87\xc2\x80\xa8\xba\xc2\x00\xa4>A\x80\x87uB\x80[!B\x00\x80\x8eA\x00\xf8\xad\xc2\xc0\xcd\x0f\xc3\x00p\x8eB\xc0t&C\x00\xf2\xdaA\x80\x8c2\xc2\x00\xf7-\xc3@\xfe\xd4\xc2\xc0\n\rC\x80\xf2\xcdB\x80R\x19\xc2\x00\xba\x98\xc2\x00I\x97\xc2\x80\xbdK\xc2\x802eB`\x88\x02C\x00\xed^B\x80!\xab\xc2@ \x1c\xc3\x00\xfa\xb6\xc1\x007\x92B\x805BB\x00J\x94A\xc0\x11\xb3\xc2\x80?`\xc2\x80\xe4\x8fB\x00\x0b\x99A\x00@\xa1\xc1\x00\xd0t@\x00\xe3\x1b\xc2\xc0\x87\x89\xc2\x00\xb2\x87A\xc0j\xd2B\x00\xd0\x92?\x80\xd2\xf4\xc2\x80^\x8d\xc2\x80\x9f\xb4B\xc0\x96\xa1B\xa0\x10\x1a\xc3@\xaa\xe6\xc2\xc0\xe0\xd9B\xa0b\x0cC\x80l_B\x00\xee\xde\xc2@\xc1\x0b\xc3\x00 0@\x00\xd7LB\x00g\xf7A\x00\xd6\x19\xc1\x00\x9eS\xc2\xc0a\x8d\xc2\x00\xd0\xcd\xc1\xc0\x08\xb0B\x80w\x9fB\x00Vl\xc2\x80\xbc\xb6\xc2\x00\x12\x9b\xc1\x80Q\x03B@\x9d\xa4B\x00\x1b=B\x00\x94\xc2\xc2`\x14\x0e\xc3\x80]\x04\xc2\x80\x8dsB\xc0\xb1\x85B\x00\x85\xb6A\x80\xfa\x9a\xc2\x80\x91\xb4\xc2\x00\xe0UB\xc0\xe2\xcaB\x00\xf4\xd8\xc1\xc0W\xd0\xc2\x00\xd4\x0e\xc1\x005"B\x80\x0c6\xc2\x80-2\xc2\x00\x97\xe9A\x00\xdb\xfe\xc1\x00\xa6\x0f\xc2\xc0]\x0cC\xc0\xa1\x8eB\xc0\x06\x0e\xc3\xc0\r\xe1\xc2\x00=#\xc2\x00\xa1<B\xa0i\x06C\x00T\xa3\xc1\x80\xf1\xf0\xc2\x00\xd9\x0c\xc2\x00\x18%\xc2\x00\x9f\xb7A\x00\xe8\xd3B\x00\xfb\xec\xc1\xc0X\xdc\xc2\x00\x9b\x92A\x80\x9e\xb0B\x00\x0e\x8a\xc1\xc0\x17\x88\xc2\x00y\xca\xc1\x00l\x7f\xc2\x80Q\xac\xc2@\xad\xa4B\xa0\xd7HC\x00\xe3\x81\xc1@\xd3}\xc3\x80%\xb7\xc2\xa0u1C\x00G\xb0B@\xde\xc1\xc2\xc0\xe5\x9f\xc2\x00\x0c\xef\xc0\xfc\x83m?M\xfe\xa0?\xff\x0e\xa0?\x1b\xa3P?i\xa4\x06?\x99n\x11?s\xf3\x05?\xddE\x0f?iWQ?\xbc+z@hA\x8d@f,\x8e@F\x1a\x95@\xaf\xaa\x90@\xed\xf3\xb2@\xb2\x88\xd0@[\x88\xc6@\xf7\x10\xfe@xc\xfc@k>\x11A\xb8>\x07A\xdc\x1f\xff@~\xbb5A\xac9PAS\xbfeA\xcd\xa9\xdeA\x05\x1d\xefA\x1fd\xf4Ak\xa9\xeeAd\x0f\xe9A\x86\r\xe2AC5$Ab\xc0<A\xbc\x9a<A\x14\xd3UA\xaf\x1c\xacA\xb0\xa0\xadA\xa6s\xb2A\x13&\xaaAx\xfa\x9fAC=\x96A\xff\xd3\\A\x103/Ao\xc1TA\x95\xf3\x04AD\xc0\x0fA\xc6[\x03A\x19\x86\x0cA Z\xf8@\xd9\xee\x90@g\x02\x90@}\xdb\xa1@\x14\xe9\x82@\x1f\x90v@\xe5\xda\x81@\x1c\x90\x80@d\xd4\x84@kOW@\xcd#I@\xe0\x0bI@\xda\x0e4@xh\x07@\xdbE\xbd?3v\xb5?\xa6\x83V?\xa1\xc0<?\xc5\xb9\x0b?\x08\xce\xde>\xf5\xd5\x8f>\t\xed\x97=\x8e\xb7\x11=\x84\xfc\x9d;\xdc\xc4\xea8\x07\t\x1f9\x17\xf8\xd39\x0c /9\xd9pt?\x87\xe3\xac?\xa5U\xa4?\xfd"B?\x0bH\xab>\x1d\x7f\x12?\xb1\xe2M?\x98\x9dx?\x9d\xbb\x8d?\xca-^@e\xedr@\x9d\x03\x89@`\x0f\x88@/\xab\x88@no\xaa@\x88\xc6\x99@\xd1\x0b\x99@~\xdd\xd7@\x07\xc8\xf0@\x10M&A\t\x9a,A\x01\x95&A\xfd\x04\x85A\xeb<\x80A\x04h\x8fAk\xc2\xfeA\xb2w\x06B\xe7\xcd\x02B\x15\x03\xf6A:\xe5\xe1A<\n\xe4A\x1a\x86KA\xac\xae*AN\xc1DAi\xbaOA/\xbdyA\xec\xf7iA\xe3SsA9\xc1LA`G|A\x00\xd5XA\xcc?SAL\x8f\x15A\xfed\'A\xf4\xc8-A\x1c\xe2\x1dA&l!AI\x90$A\xc6G\x19A\xcd\x96\xe8@\xcf\x18\x0cA\xf3\xb7\x02A\xc4\xd1\x02A\x91=\xf3@nh\xd4@!"\xd3@\x91\x11^@\x95Ab@\t\x83c@\x0b\x88U@;\xbe6@{z)@\x1f\x0e+@\xfe\x00\xf9?\x177\xcc?\xad\xe0{?\xc7\x97\'?\xa9\xc8\x14?N}\x82>\xa0%C>\xf9v\x1c<A,\xaf:\n\x90.9\x805\x899S\x9cd9\xb7Vp9\x10\x07\x00\x00\x0c\x01\x00\x00AVM                                     HHZ CI                                              \xe1.\x00\x00\xe3\x07\x00\x00\x07\x00\x00\x00\x04\x00\x00\x00\x11\x00\x00\x006\x00\x00\x00\x00\x00\xc6\xc2\x00\x00\xc6\xc2\x00\x00\x80?\x00\x00\x80\xbf\x00\x00\x80\xbf\n\xd7#<7\xdacB\xcc\xff\xef\xc12C\x0cB";\xe9\xc2\x00 1D!\x0by?\xb5\xff\x98C\x9c\xe0\xfaB\x9a\x0f>B\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc6\xc2\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0c\x01\x00\x00\x10\x07\x00\x00\x10M\xc3C\xb4\xb6\xd9C(\xdf\xccC\xec\xa5\x94C\x80Y\'C\xf0\xd2\xa1B\xe0\xe9\x03B\x00\x9e\xce\xc0\x00\x94I\xc2\x00+\xaf\xc2\x80\n\xba\xc2\xa0\xcfo\xc2\x00U\xe4\xc0\xa0\xb9dBp\x80\x07C\xa0\x12HC\xd8\xa2SC\xc8q5C\x98\x01\x18CHR\tC\x00F\xf5B\x00\xe6\xc2B@\x86\x92B\xc0OeB\xe0\x91\x18B\x80L\x17A@\xda\xe9\xc1\x80\xd7\x83\xc2\xe0\xb5\x9b\xc2\xe0\x12\x9b\xc2\xc0\xf2\xc0\xc2\xd0\xd3\xfa\xc2\x80\xd9\t\xc3\xc0\xc8\x06\xc3\xb0\xf0\xfb\xc2p\xcf\xd7\xc2\x90-\xa6\xc2@\x1al\xc2\